### ISSUE TITLE
Sound does not play in safari 

### ISSUE THREAD

**Issue by omrynskyi** [omrynskyi/mux-pad#1]

**Comment by omrynskyi** [comment]
error occurred

TypeError: Not enough arguments
decodeAudioData
w — runtime.js:82
(anonymous function) — runtime.js:300
i — asyncToGenerator.js:15
c — asyncToGenerator.js:31
promiseReactionJob

**Comment by amrynsky** [comment]
Safari doesn't support promise based interface for decodeAudioData. Callback API should be used instead
https://stackoverflow.com/questions/48597747/how-to-play-a-sound-file-safari-with-web-audio-api/48597898#48597898
